-- Create queue table for realtime embedding generation
CREATE TABLE IF NOT EXISTS public.embedding_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_id UUID NOT NULL,
  content_type TEXT NOT NULL CHECK (content_type IN ('seed','message','conversation')),
  content_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Allow realtime broadcasts for the queue
ALTER PUBLICATION supabase_realtime ADD TABLE public.embedding_jobs;
